// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: async_ops.proto

package asyncops

import (
	common "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/common"
	_ "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An `AsyncOp` state update.
//
// This includes a list of any new async ops, and updates to the associated statistics
// for any async ops that have changed since the last update.
type AsyncOpUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of new async operations that were created since the last `AsyncOpUpdate`
	// was sent. Note that the fact that an async operation has been created
	// does not mean that is has been polled or is being polled. This information
	// is reflected in the `Stats` of the operation.
	NewAsyncOps []*AsyncOp `protobuf:"bytes,1,rep,name=new_async_ops,json=newAsyncOps,proto3" json:"new_async_ops,omitempty"`
	// Any async op stats that have changed since the last update.
	StatsUpdate map[uint64]*Stats `protobuf:"bytes,2,rep,name=stats_update,json=statsUpdate,proto3" json:"stats_update,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A count of how many async op events (e.g. polls, creation, etc) were not
	// recorded because the application's event buffer was at capacity.
	//
	// If everything is working normally, this should be 0. If it is greater
	// than 0, that may indicate that some data is missing from this update, and
	// it may be necessary to increase the number of events buffered by the
	// application to ensure that data loss is avoided.
	//
	// If the application's instrumentation ensures reliable delivery of events,
	// this will always be 0.
	DroppedEvents uint64 `protobuf:"varint,3,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncOpUpdate) Reset() {
	*x = AsyncOpUpdate{}
	mi := &file_async_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncOpUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncOpUpdate) ProtoMessage() {}

func (x *AsyncOpUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_async_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncOpUpdate.ProtoReflect.Descriptor instead.
func (*AsyncOpUpdate) Descriptor() ([]byte, []int) {
	return file_async_ops_proto_rawDescGZIP(), []int{0}
}

func (x *AsyncOpUpdate) GetNewAsyncOps() []*AsyncOp {
	if x != nil {
		return x.NewAsyncOps
	}
	return nil
}

func (x *AsyncOpUpdate) GetStatsUpdate() map[uint64]*Stats {
	if x != nil {
		return x.StatsUpdate
	}
	return nil
}

func (x *AsyncOpUpdate) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

// An async operation.
//
// An async operation is an operation that is associated with a resource
// This could, for example, be a read or write on a TCP stream, or a receive operation on
// a channel.
type AsyncOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The async op's ID.
	//
	// This uniquely identifies this op across all *currently live*
	// ones.
	Id *common.Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The numeric ID of the op's `Metadata`.
	//
	// This identifies the `Metadata` that describes the `tracing` span
	// corresponding to this async op. The metadata for this ID will have been sent
	// in a prior `RegisterMetadata` message.
	Metadata *common.MetaId `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The source of this async operation. Most commonly this should be the name
	// of the method where the instantiation of this op has happened.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// The ID of the parent async op.
	//
	// This field is only set if this async op was created while inside of another
	// async op.  For example, `tokio::sync`'s `Mutex::lock` internally calls
	// `Semaphore::acquire`.
	//
	// This field can be empty; if it is empty, this async op is not a child of another
	// async op.
	ParentAsyncOpId *common.Id `protobuf:"bytes,4,opt,name=parent_async_op_id,json=parentAsyncOpId,proto3" json:"parent_async_op_id,omitempty"`
	// The resources's ID.
	ResourceId    *common.Id `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncOp) Reset() {
	*x = AsyncOp{}
	mi := &file_async_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncOp) ProtoMessage() {}

func (x *AsyncOp) ProtoReflect() protoreflect.Message {
	mi := &file_async_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncOp.ProtoReflect.Descriptor instead.
func (*AsyncOp) Descriptor() ([]byte, []int) {
	return file_async_ops_proto_rawDescGZIP(), []int{1}
}

func (x *AsyncOp) GetId() *common.Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AsyncOp) GetMetadata() *common.MetaId {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AsyncOp) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AsyncOp) GetParentAsyncOpId() *common.Id {
	if x != nil {
		return x.ParentAsyncOpId
	}
	return nil
}

func (x *AsyncOp) GetResourceId() *common.Id {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

// Statistics associated with a given async operation.
type Stats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of when the async op has been created.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of when the async op was dropped.
	DroppedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=dropped_at,json=droppedAt,proto3" json:"dropped_at,omitempty"`
	// The Id of the task that is awaiting on this op.
	TaskId *common.Id `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Contains the operation poll stats.
	PollStats *common.PollStats `protobuf:"bytes,5,opt,name=poll_stats,json=pollStats,proto3" json:"poll_stats,omitempty"`
	// State attributes of the async op.
	Attributes    []*common.Attribute `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_async_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_async_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_async_ops_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stats) GetDroppedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DroppedAt
	}
	return nil
}

func (x *Stats) GetTaskId() *common.Id {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *Stats) GetPollStats() *common.PollStats {
	if x != nil {
		return x.PollStats
	}
	return nil
}

func (x *Stats) GetAttributes() []*common.Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_async_ops_proto protoreflect.FileDescriptor

const file_async_ops_proto_rawDesc = "" +
	"\n" +
	"\x0fasync_ops.proto\x12\x1ars.tokio.console.async_ops\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\fcommon.proto\"\xc1\x02\n" +
	"\rAsyncOpUpdate\x12G\n" +
	"\rnew_async_ops\x18\x01 \x03(\v2#.rs.tokio.console.async_ops.AsyncOpR\vnewAsyncOps\x12]\n" +
	"\fstats_update\x18\x02 \x03(\v2:.rs.tokio.console.async_ops.AsyncOpUpdate.StatsUpdateEntryR\vstatsUpdate\x12%\n" +
	"\x0edropped_events\x18\x03 \x01(\x04R\rdroppedEvents\x1aa\n" +
	"\x10StatsUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.rs.tokio.console.async_ops.StatsR\x05value:\x028\x01\"\x93\x02\n" +
	"\aAsyncOp\x12+\n" +
	"\x02id\x18\x01 \x01(\v2\x1b.rs.tokio.console.common.IdR\x02id\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\bmetadata\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12H\n" +
	"\x12parent_async_op_id\x18\x04 \x01(\v2\x1b.rs.tokio.console.common.IdR\x0fparentAsyncOpId\x12<\n" +
	"\vresource_id\x18\x05 \x01(\v2\x1b.rs.tokio.console.common.IdR\n" +
	"resourceId\"\xba\x02\n" +
	"\x05Stats\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"dropped_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdroppedAt\x124\n" +
	"\atask_id\x18\x04 \x01(\v2\x1b.rs.tokio.console.common.IdR\x06taskId\x12A\n" +
	"\n" +
	"poll_stats\x18\x05 \x01(\v2\".rs.tokio.console.common.PollStatsR\tpollStats\x12B\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\".rs.tokio.console.common.AttributeR\n" +
	"attributesb\x06proto3"

var (
	file_async_ops_proto_rawDescOnce sync.Once
	file_async_ops_proto_rawDescData []byte
)

func file_async_ops_proto_rawDescGZIP() []byte {
	file_async_ops_proto_rawDescOnce.Do(func() {
		file_async_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_async_ops_proto_rawDesc), len(file_async_ops_proto_rawDesc)))
	})
	return file_async_ops_proto_rawDescData
}

var file_async_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_async_ops_proto_goTypes = []any{
	(*AsyncOpUpdate)(nil),       // 0: rs.tokio.console.async_ops.AsyncOpUpdate
	(*AsyncOp)(nil),             // 1: rs.tokio.console.async_ops.AsyncOp
	(*Stats)(nil),               // 2: rs.tokio.console.async_ops.Stats
	nil,                         // 3: rs.tokio.console.async_ops.AsyncOpUpdate.StatsUpdateEntry
	(*common.Id)(nil),           // 4: rs.tokio.console.common.Id
	(*common.MetaId)(nil),       // 5: rs.tokio.console.common.MetaId
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*common.PollStats)(nil),    // 7: rs.tokio.console.common.PollStats
	(*common.Attribute)(nil),    // 8: rs.tokio.console.common.Attribute
}
var file_async_ops_proto_depIdxs = []int32{
	1,  // 0: rs.tokio.console.async_ops.AsyncOpUpdate.new_async_ops:type_name -> rs.tokio.console.async_ops.AsyncOp
	3,  // 1: rs.tokio.console.async_ops.AsyncOpUpdate.stats_update:type_name -> rs.tokio.console.async_ops.AsyncOpUpdate.StatsUpdateEntry
	4,  // 2: rs.tokio.console.async_ops.AsyncOp.id:type_name -> rs.tokio.console.common.Id
	5,  // 3: rs.tokio.console.async_ops.AsyncOp.metadata:type_name -> rs.tokio.console.common.MetaId
	4,  // 4: rs.tokio.console.async_ops.AsyncOp.parent_async_op_id:type_name -> rs.tokio.console.common.Id
	4,  // 5: rs.tokio.console.async_ops.AsyncOp.resource_id:type_name -> rs.tokio.console.common.Id
	6,  // 6: rs.tokio.console.async_ops.Stats.created_at:type_name -> google.protobuf.Timestamp
	6,  // 7: rs.tokio.console.async_ops.Stats.dropped_at:type_name -> google.protobuf.Timestamp
	4,  // 8: rs.tokio.console.async_ops.Stats.task_id:type_name -> rs.tokio.console.common.Id
	7,  // 9: rs.tokio.console.async_ops.Stats.poll_stats:type_name -> rs.tokio.console.common.PollStats
	8,  // 10: rs.tokio.console.async_ops.Stats.attributes:type_name -> rs.tokio.console.common.Attribute
	2,  // 11: rs.tokio.console.async_ops.AsyncOpUpdate.StatsUpdateEntry.value:type_name -> rs.tokio.console.async_ops.Stats
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_async_ops_proto_init() }
func file_async_ops_proto_init() {
	if File_async_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_async_ops_proto_rawDesc), len(file_async_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_async_ops_proto_goTypes,
		DependencyIndexes: file_async_ops_proto_depIdxs,
		MessageInfos:      file_async_ops_proto_msgTypes,
	}.Build()
	File_async_ops_proto = out.File
	file_async_ops_proto_goTypes = nil
	file_async_ops_proto_depIdxs = nil
}
