// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: instrument.proto

package instrument

import (
	asyncops "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/asyncops"
	common "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/common"
	resources "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/resources"
	tasks "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/tasks"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The time "state" of the aggregator.
type Temporality int32

const (
	// The aggregator is currently live.
	Temporality_LIVE Temporality = 0
	// The aggregator is currently paused.
	Temporality_PAUSED Temporality = 1
)

// Enum value maps for Temporality.
var (
	Temporality_name = map[int32]string{
		0: "LIVE",
		1: "PAUSED",
	}
	Temporality_value = map[string]int32{
		"LIVE":   0,
		"PAUSED": 1,
	}
)

func (x Temporality) Enum() *Temporality {
	p := new(Temporality)
	*p = x
	return p
}

func (x Temporality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Temporality) Descriptor() protoreflect.EnumDescriptor {
	return file_instrument_proto_enumTypes[0].Descriptor()
}

func (Temporality) Type() protoreflect.EnumType {
	return &file_instrument_proto_enumTypes[0]
}

func (x Temporality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Temporality.Descriptor instead.
func (Temporality) EnumDescriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{0}
}

// InstrumentRequest requests the stream of updates
// to observe the async runtime state over time.
//
// TODO: In the future allow for the request to specify
// only the data that the caller cares about (i.e. only
// tasks but no resources)
type InstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentRequest) Reset() {
	*x = InstrumentRequest{}
	mi := &file_instrument_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentRequest) ProtoMessage() {}

func (x *InstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentRequest.ProtoReflect.Descriptor instead.
func (*InstrumentRequest) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{0}
}

// TaskDetailsRequest requests the stream of updates about
// the specific task identified in the request.
type TaskDetailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the task for which details were requested.
	Id            *common.Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetailsRequest) Reset() {
	*x = TaskDetailsRequest{}
	mi := &file_instrument_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailsRequest) ProtoMessage() {}

func (x *TaskDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailsRequest.ProtoReflect.Descriptor instead.
func (*TaskDetailsRequest) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{1}
}

func (x *TaskDetailsRequest) GetId() *common.Id {
	if x != nil {
		return x.Id
	}
	return nil
}

// PauseRequest requests the stream of updates to pause.
type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_instrument_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{2}
}

// ResumeRequest requests the stream of updates to resume after a pause.
type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_instrument_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{3}
}

// Update carries all information regarding tasks, resources, async operations
// and resource operations in one message. There are a couple of reasons to combine all
// of these into a single message:
//
//   - we can use one single timestamp for all the data
//   - we can have all the new_metadata in one place
//   - things such as async ops and resource ops do not make sense
//     on their own as they have relations to tasks and resources
type Update struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The system time when this update was recorded.
	//
	// This is the timestamp any durations in the included `Stats` were
	// calculated relative to.
	Now *timestamp.Timestamp `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	// Task state update.
	TaskUpdate *tasks.TaskUpdate `protobuf:"bytes,2,opt,name=task_update,json=taskUpdate,proto3" json:"task_update,omitempty"`
	// Resource state update.
	ResourceUpdate *resources.ResourceUpdate `protobuf:"bytes,3,opt,name=resource_update,json=resourceUpdate,proto3" json:"resource_update,omitempty"`
	// Async operations state update
	AsyncOpUpdate *asyncops.AsyncOpUpdate `protobuf:"bytes,4,opt,name=async_op_update,json=asyncOpUpdate,proto3" json:"async_op_update,omitempty"`
	// Any new span metadata that was registered since the last update.
	NewMetadata   *common.RegisterMetadata `protobuf:"bytes,5,opt,name=new_metadata,json=newMetadata,proto3" json:"new_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_instrument_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{4}
}

func (x *Update) GetNow() *timestamp.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *Update) GetTaskUpdate() *tasks.TaskUpdate {
	if x != nil {
		return x.TaskUpdate
	}
	return nil
}

func (x *Update) GetResourceUpdate() *resources.ResourceUpdate {
	if x != nil {
		return x.ResourceUpdate
	}
	return nil
}

func (x *Update) GetAsyncOpUpdate() *asyncops.AsyncOpUpdate {
	if x != nil {
		return x.AsyncOpUpdate
	}
	return nil
}

func (x *Update) GetNewMetadata() *common.RegisterMetadata {
	if x != nil {
		return x.NewMetadata
	}
	return nil
}

// StateRequest requests the current state of the aggregator.
type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_instrument_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{5}
}

// State carries the current state of the aggregator.
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temporality   Temporality            `protobuf:"varint,1,opt,name=temporality,proto3,enum=rs.tokio.console.instrument.Temporality" json:"temporality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_instrument_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{6}
}

func (x *State) GetTemporality() Temporality {
	if x != nil {
		return x.Temporality
	}
	return Temporality_LIVE
}

// `PauseResponse` is the value returned after a pause request.
type PauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResponse) Reset() {
	*x = PauseResponse{}
	mi := &file_instrument_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResponse) ProtoMessage() {}

func (x *PauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResponse.ProtoReflect.Descriptor instead.
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{7}
}

// `ResumeResponse` is the value returned after a resume request.
type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_instrument_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{8}
}

var File_instrument_proto protoreflect.FileDescriptor

const file_instrument_proto_rawDesc = "" +
	"\n" +
	"\x10instrument.proto\x12\x1brs.tokio.console.instrument\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\vtasks.proto\x1a\x0fresources.proto\x1a\x0fasync_ops.proto\"\x13\n" +
	"\x11InstrumentRequest\"A\n" +
	"\x12TaskDetailsRequest\x12+\n" +
	"\x02id\x18\x01 \x01(\v2\x1b.rs.tokio.console.common.IdR\x02id\"\x0e\n" +
	"\fPauseRequest\"\x0f\n" +
	"\rResumeRequest\"\xf1\x02\n" +
	"\x06Update\x12,\n" +
	"\x03now\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\x12C\n" +
	"\vtask_update\x18\x02 \x01(\v2\".rs.tokio.console.tasks.TaskUpdateR\n" +
	"taskUpdate\x12S\n" +
	"\x0fresource_update\x18\x03 \x01(\v2*.rs.tokio.console.resources.ResourceUpdateR\x0eresourceUpdate\x12Q\n" +
	"\x0fasync_op_update\x18\x04 \x01(\v2).rs.tokio.console.async_ops.AsyncOpUpdateR\rasyncOpUpdate\x12L\n" +
	"\fnew_metadata\x18\x05 \x01(\v2).rs.tokio.console.common.RegisterMetadataR\vnewMetadata\"\x0e\n" +
	"\fStateRequest\"S\n" +
	"\x05State\x12J\n" +
	"\vtemporality\x18\x01 \x01(\x0e2(.rs.tokio.console.instrument.TemporalityR\vtemporality\"\x0f\n" +
	"\rPauseResponse\"\x10\n" +
	"\x0eResumeResponse*#\n" +
	"\vTemporality\x12\b\n" +
	"\x04LIVE\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x012\x8b\x04\n" +
	"\n" +
	"Instrument\x12g\n" +
	"\fWatchUpdates\x12..rs.tokio.console.instrument.InstrumentRequest\x1a#.rs.tokio.console.instrument.Update\"\x000\x01\x12l\n" +
	"\x10WatchTaskDetails\x12/.rs.tokio.console.instrument.TaskDetailsRequest\x1a#.rs.tokio.console.tasks.TaskDetails\"\x000\x01\x12_\n" +
	"\n" +
	"WatchState\x12).rs.tokio.console.instrument.StateRequest\x1a\".rs.tokio.console.instrument.State\"\x000\x01\x12`\n" +
	"\x05Pause\x12).rs.tokio.console.instrument.PauseRequest\x1a*.rs.tokio.console.instrument.PauseResponse\"\x00\x12c\n" +
	"\x06Resume\x12*.rs.tokio.console.instrument.ResumeRequest\x1a+.rs.tokio.console.instrument.ResumeResponse\"\x00b\x06proto3"

var (
	file_instrument_proto_rawDescOnce sync.Once
	file_instrument_proto_rawDescData []byte
)

func file_instrument_proto_rawDescGZIP() []byte {
	file_instrument_proto_rawDescOnce.Do(func() {
		file_instrument_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instrument_proto_rawDesc), len(file_instrument_proto_rawDesc)))
	})
	return file_instrument_proto_rawDescData
}

var file_instrument_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instrument_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_instrument_proto_goTypes = []any{
	(Temporality)(0),                 // 0: rs.tokio.console.instrument.Temporality
	(*InstrumentRequest)(nil),        // 1: rs.tokio.console.instrument.InstrumentRequest
	(*TaskDetailsRequest)(nil),       // 2: rs.tokio.console.instrument.TaskDetailsRequest
	(*PauseRequest)(nil),             // 3: rs.tokio.console.instrument.PauseRequest
	(*ResumeRequest)(nil),            // 4: rs.tokio.console.instrument.ResumeRequest
	(*Update)(nil),                   // 5: rs.tokio.console.instrument.Update
	(*StateRequest)(nil),             // 6: rs.tokio.console.instrument.StateRequest
	(*State)(nil),                    // 7: rs.tokio.console.instrument.State
	(*PauseResponse)(nil),            // 8: rs.tokio.console.instrument.PauseResponse
	(*ResumeResponse)(nil),           // 9: rs.tokio.console.instrument.ResumeResponse
	(*common.Id)(nil),                // 10: rs.tokio.console.common.Id
	(*timestamp.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*tasks.TaskUpdate)(nil),         // 12: rs.tokio.console.tasks.TaskUpdate
	(*resources.ResourceUpdate)(nil), // 13: rs.tokio.console.resources.ResourceUpdate
	(*asyncops.AsyncOpUpdate)(nil),   // 14: rs.tokio.console.async_ops.AsyncOpUpdate
	(*common.RegisterMetadata)(nil),  // 15: rs.tokio.console.common.RegisterMetadata
	(*tasks.TaskDetails)(nil),        // 16: rs.tokio.console.tasks.TaskDetails
}
var file_instrument_proto_depIdxs = []int32{
	10, // 0: rs.tokio.console.instrument.TaskDetailsRequest.id:type_name -> rs.tokio.console.common.Id
	11, // 1: rs.tokio.console.instrument.Update.now:type_name -> google.protobuf.Timestamp
	12, // 2: rs.tokio.console.instrument.Update.task_update:type_name -> rs.tokio.console.tasks.TaskUpdate
	13, // 3: rs.tokio.console.instrument.Update.resource_update:type_name -> rs.tokio.console.resources.ResourceUpdate
	14, // 4: rs.tokio.console.instrument.Update.async_op_update:type_name -> rs.tokio.console.async_ops.AsyncOpUpdate
	15, // 5: rs.tokio.console.instrument.Update.new_metadata:type_name -> rs.tokio.console.common.RegisterMetadata
	0,  // 6: rs.tokio.console.instrument.State.temporality:type_name -> rs.tokio.console.instrument.Temporality
	1,  // 7: rs.tokio.console.instrument.Instrument.WatchUpdates:input_type -> rs.tokio.console.instrument.InstrumentRequest
	2,  // 8: rs.tokio.console.instrument.Instrument.WatchTaskDetails:input_type -> rs.tokio.console.instrument.TaskDetailsRequest
	6,  // 9: rs.tokio.console.instrument.Instrument.WatchState:input_type -> rs.tokio.console.instrument.StateRequest
	3,  // 10: rs.tokio.console.instrument.Instrument.Pause:input_type -> rs.tokio.console.instrument.PauseRequest
	4,  // 11: rs.tokio.console.instrument.Instrument.Resume:input_type -> rs.tokio.console.instrument.ResumeRequest
	5,  // 12: rs.tokio.console.instrument.Instrument.WatchUpdates:output_type -> rs.tokio.console.instrument.Update
	16, // 13: rs.tokio.console.instrument.Instrument.WatchTaskDetails:output_type -> rs.tokio.console.tasks.TaskDetails
	7,  // 14: rs.tokio.console.instrument.Instrument.WatchState:output_type -> rs.tokio.console.instrument.State
	8,  // 15: rs.tokio.console.instrument.Instrument.Pause:output_type -> rs.tokio.console.instrument.PauseResponse
	9,  // 16: rs.tokio.console.instrument.Instrument.Resume:output_type -> rs.tokio.console.instrument.ResumeResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_instrument_proto_init() }
func file_instrument_proto_init() {
	if File_instrument_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instrument_proto_rawDesc), len(file_instrument_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_instrument_proto_goTypes,
		DependencyIndexes: file_instrument_proto_depIdxs,
		EnumInfos:         file_instrument_proto_enumTypes,
		MessageInfos:      file_instrument_proto_msgTypes,
	}.Build()
	File_instrument_proto = out.File
	file_instrument_proto_goTypes = nil
	file_instrument_proto_depIdxs = nil
}
