// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: instrument.proto

package instrument

import (
	context "context"
	tasks "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/tasks"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Instrument_WatchUpdates_FullMethodName     = "/rs.tokio.console.instrument.Instrument/WatchUpdates"
	Instrument_WatchTaskDetails_FullMethodName = "/rs.tokio.console.instrument.Instrument/WatchTaskDetails"
	Instrument_WatchState_FullMethodName       = "/rs.tokio.console.instrument.Instrument/WatchState"
	Instrument_Pause_FullMethodName            = "/rs.tokio.console.instrument.Instrument/Pause"
	Instrument_Resume_FullMethodName           = "/rs.tokio.console.instrument.Instrument/Resume"
)

// InstrumentClient is the client API for Instrument service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// `InstrumentServer<T>` implements `Instrument` as a service.
type InstrumentClient interface {
	// Produces a stream of updates representing the behavior of the instrumented async runtime.
	WatchUpdates(ctx context.Context, in *InstrumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Update], error)
	// Produces a stream of updates describing the activity of a specific task.
	WatchTaskDetails(ctx context.Context, in *TaskDetailsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[tasks.TaskDetails], error)
	// Produces a stream of state of the aggregator.
	WatchState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[State], error)
	// Registers that the console observer wants to pause the stream.
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	// Registers that the console observer wants to resume the stream.
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
}

type instrumentClient struct {
	cc grpc.ClientConnInterface
}

func NewInstrumentClient(cc grpc.ClientConnInterface) InstrumentClient {
	return &instrumentClient{cc}
}

func (c *instrumentClient) WatchUpdates(ctx context.Context, in *InstrumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Update], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Instrument_ServiceDesc.Streams[0], Instrument_WatchUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstrumentRequest, Update]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Instrument_WatchUpdatesClient = grpc.ServerStreamingClient[Update]

func (c *instrumentClient) WatchTaskDetails(ctx context.Context, in *TaskDetailsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[tasks.TaskDetails], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Instrument_ServiceDesc.Streams[1], Instrument_WatchTaskDetails_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskDetailsRequest, tasks.TaskDetails]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Instrument_WatchTaskDetailsClient = grpc.ServerStreamingClient[tasks.TaskDetails]

func (c *instrumentClient) WatchState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[State], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Instrument_ServiceDesc.Streams[2], Instrument_WatchState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateRequest, State]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Instrument_WatchStateClient = grpc.ServerStreamingClient[State]

func (c *instrumentClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseResponse)
	err := c.cc.Invoke(ctx, Instrument_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, Instrument_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstrumentServer is the server API for Instrument service.
// All implementations must embed UnimplementedInstrumentServer
// for forward compatibility.
//
// `InstrumentServer<T>` implements `Instrument` as a service.
type InstrumentServer interface {
	// Produces a stream of updates representing the behavior of the instrumented async runtime.
	WatchUpdates(*InstrumentRequest, grpc.ServerStreamingServer[Update]) error
	// Produces a stream of updates describing the activity of a specific task.
	WatchTaskDetails(*TaskDetailsRequest, grpc.ServerStreamingServer[tasks.TaskDetails]) error
	// Produces a stream of state of the aggregator.
	WatchState(*StateRequest, grpc.ServerStreamingServer[State]) error
	// Registers that the console observer wants to pause the stream.
	Pause(context.Context, *PauseRequest) (*PauseResponse, error)
	// Registers that the console observer wants to resume the stream.
	Resume(context.Context, *ResumeRequest) (*ResumeResponse, error)
	mustEmbedUnimplementedInstrumentServer()
}

// UnimplementedInstrumentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstrumentServer struct{}

func (UnimplementedInstrumentServer) WatchUpdates(*InstrumentRequest, grpc.ServerStreamingServer[Update]) error {
	return status.Error(codes.Unimplemented, "method WatchUpdates not implemented")
}
func (UnimplementedInstrumentServer) WatchTaskDetails(*TaskDetailsRequest, grpc.ServerStreamingServer[tasks.TaskDetails]) error {
	return status.Error(codes.Unimplemented, "method WatchTaskDetails not implemented")
}
func (UnimplementedInstrumentServer) WatchState(*StateRequest, grpc.ServerStreamingServer[State]) error {
	return status.Error(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedInstrumentServer) Pause(context.Context, *PauseRequest) (*PauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedInstrumentServer) Resume(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedInstrumentServer) mustEmbedUnimplementedInstrumentServer() {}
func (UnimplementedInstrumentServer) testEmbeddedByValue()                    {}

// UnsafeInstrumentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstrumentServer will
// result in compilation errors.
type UnsafeInstrumentServer interface {
	mustEmbedUnimplementedInstrumentServer()
}

func RegisterInstrumentServer(s grpc.ServiceRegistrar, srv InstrumentServer) {
	// If the following call panics, it indicates UnimplementedInstrumentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Instrument_ServiceDesc, srv)
}

func _Instrument_WatchUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstrumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstrumentServer).WatchUpdates(m, &grpc.GenericServerStream[InstrumentRequest, Update]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Instrument_WatchUpdatesServer = grpc.ServerStreamingServer[Update]

func _Instrument_WatchTaskDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskDetailsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstrumentServer).WatchTaskDetails(m, &grpc.GenericServerStream[TaskDetailsRequest, tasks.TaskDetails]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Instrument_WatchTaskDetailsServer = grpc.ServerStreamingServer[tasks.TaskDetails]

func _Instrument_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstrumentServer).WatchState(m, &grpc.GenericServerStream[StateRequest, State]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Instrument_WatchStateServer = grpc.ServerStreamingServer[State]

func _Instrument_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Instrument_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instrument_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Instrument_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Instrument_ServiceDesc is the grpc.ServiceDesc for Instrument service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Instrument_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rs.tokio.console.instrument.Instrument",
	HandlerType: (*InstrumentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pause",
			Handler:    _Instrument_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Instrument_Resume_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchUpdates",
			Handler:       _Instrument_WatchUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTaskDetails",
			Handler:       _Instrument_WatchTaskDetails_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchState",
			Handler:       _Instrument_WatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "instrument.proto",
}
