// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: common.proto

package common

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Indicates whether metadata is associated with a span or with an event.
type Metadata_Kind int32

const (
	// Indicates metadata is associated with a span.
	Metadata_SPAN Metadata_Kind = 0
	// Indicates metadata is associated with an event.
	Metadata_EVENT Metadata_Kind = 1
)

// Enum value maps for Metadata_Kind.
var (
	Metadata_Kind_name = map[int32]string{
		0: "SPAN",
		1: "EVENT",
	}
	Metadata_Kind_value = map[string]int32{
		"SPAN":  0,
		"EVENT": 1,
	}
)

func (x Metadata_Kind) Enum() *Metadata_Kind {
	p := new(Metadata_Kind)
	*p = x
	return p
}

func (x Metadata_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadata_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Metadata_Kind) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Metadata_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadata_Kind.Descriptor instead.
func (Metadata_Kind) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7, 0}
}

// Describes the level of verbosity of a span or event.
//
// Corresponds to `Level` in the `tracing` crate.
type Metadata_Level int32

const (
	// The "error" level.
	//
	// Designates very serious errors.
	Metadata_ERROR Metadata_Level = 0
	// The "warn" level.
	//
	// Designates hazardous situations.
	Metadata_WARN Metadata_Level = 1
	// The "info" level.
	// Designates useful information.
	Metadata_INFO Metadata_Level = 2
	// The "debug" level.
	//
	// Designates lower priority information.
	Metadata_DEBUG Metadata_Level = 3
	// The "trace" level.
	//
	// Designates very low priority, often extremely verbose, information.
	Metadata_TRACE Metadata_Level = 4
)

// Enum value maps for Metadata_Level.
var (
	Metadata_Level_name = map[int32]string{
		0: "ERROR",
		1: "WARN",
		2: "INFO",
		3: "DEBUG",
		4: "TRACE",
	}
	Metadata_Level_value = map[string]int32{
		"ERROR": 0,
		"WARN":  1,
		"INFO":  2,
		"DEBUG": 3,
		"TRACE": 4,
	}
)

func (x Metadata_Level) Enum() *Metadata_Level {
	p := new(Metadata_Level)
	*p = x
	return p
}

func (x Metadata_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadata_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Metadata_Level) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Metadata_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadata_Level.Descriptor instead.
func (Metadata_Level) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7, 1}
}

// Unique identifier for each task.
type Id struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier's concrete value.
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// A Rust source code location.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file path
	File *string `protobuf:"bytes,1,opt,name=file,proto3,oneof" json:"file,omitempty"`
	// The Rust module path
	ModulePath *string `protobuf:"bytes,2,opt,name=module_path,json=modulePath,proto3,oneof" json:"module_path,omitempty"`
	// The line number in the source code file.
	Line *uint32 `protobuf:"varint,3,opt,name=line,proto3,oneof" json:"line,omitempty"`
	// The character in `line`.
	Column        *uint32 `protobuf:"varint,4,opt,name=column,proto3,oneof" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

func (x *Location) GetModulePath() string {
	if x != nil && x.ModulePath != nil {
		return *x.ModulePath
	}
	return ""
}

func (x *Location) GetLine() uint32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *Location) GetColumn() uint32 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

// Unique identifier for metadata.
type MetaId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier's concrete value.
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaId) Reset() {
	*x = MetaId{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaId) ProtoMessage() {}

func (x *MetaId) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaId.ProtoReflect.Descriptor instead.
func (*MetaId) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *MetaId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Unique identifier for spans.
type SpanId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier's concrete value.
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanId) Reset() {
	*x = SpanId{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanId) ProtoMessage() {}

func (x *SpanId) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanId.ProtoReflect.Descriptor instead.
func (*SpanId) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *SpanId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// A message representing a key-value pair of data associated with a `Span`
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the key-value pair.
	//
	// This is either represented as a string, or as an index into a `Metadata`'s
	// array of field name strings.
	//
	// Types that are valid to be assigned to Name:
	//
	//	*Field_StrName
	//	*Field_NameIdx
	Name isField_Name `protobuf_oneof:"name"`
	// The value of the key-value pair.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Field_DebugVal
	//	*Field_StrVal
	//	*Field_U64Val
	//	*Field_I64Val
	//	*Field_BoolVal
	Value isField_Value `protobuf_oneof:"value"`
	// Metadata for the task span that the field came from.
	MetadataId    *MetaId `protobuf:"bytes,8,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Field) GetName() isField_Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Field) GetStrName() string {
	if x != nil {
		if x, ok := x.Name.(*Field_StrName); ok {
			return x.StrName
		}
	}
	return ""
}

func (x *Field) GetNameIdx() uint64 {
	if x != nil {
		if x, ok := x.Name.(*Field_NameIdx); ok {
			return x.NameIdx
		}
	}
	return 0
}

func (x *Field) GetValue() isField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Field) GetDebugVal() string {
	if x != nil {
		if x, ok := x.Value.(*Field_DebugVal); ok {
			return x.DebugVal
		}
	}
	return ""
}

func (x *Field) GetStrVal() string {
	if x != nil {
		if x, ok := x.Value.(*Field_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *Field) GetU64Val() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Field_U64Val); ok {
			return x.U64Val
		}
	}
	return 0
}

func (x *Field) GetI64Val() int64 {
	if x != nil {
		if x, ok := x.Value.(*Field_I64Val); ok {
			return x.I64Val
		}
	}
	return 0
}

func (x *Field) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*Field_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Field) GetMetadataId() *MetaId {
	if x != nil {
		return x.MetadataId
	}
	return nil
}

type isField_Name interface {
	isField_Name()
}

type Field_StrName struct {
	// The string representation of the name.
	StrName string `protobuf:"bytes,1,opt,name=str_name,json=strName,proto3,oneof"`
}

type Field_NameIdx struct {
	// An index position into the `Metadata.field_names` of the metadata
	// for the task span that the field came from.
	NameIdx uint64 `protobuf:"varint,2,opt,name=name_idx,json=nameIdx,proto3,oneof"`
}

func (*Field_StrName) isField_Name() {}

func (*Field_NameIdx) isField_Name() {}

type isField_Value interface {
	isField_Value()
}

type Field_DebugVal struct {
	// A value serialized to a string using `fmt::Debug`.
	DebugVal string `protobuf:"bytes,3,opt,name=debug_val,json=debugVal,proto3,oneof"`
}

type Field_StrVal struct {
	// A string value.
	StrVal string `protobuf:"bytes,4,opt,name=str_val,json=strVal,proto3,oneof"`
}

type Field_U64Val struct {
	// An unsigned integer value.
	U64Val uint64 `protobuf:"varint,5,opt,name=u64_val,json=u64Val,proto3,oneof"`
}

type Field_I64Val struct {
	// A signed integer value.
	I64Val int64 `protobuf:"zigzag64,6,opt,name=i64_val,json=i64Val,proto3,oneof"`
}

type Field_BoolVal struct {
	// A boolean value.
	BoolVal bool `protobuf:"varint,7,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

func (*Field_DebugVal) isField_Value() {}

func (*Field_StrVal) isField_Value() {}

func (*Field_U64Val) isField_Value() {}

func (*Field_I64Val) isField_Value() {}

func (*Field_BoolVal) isField_Value() {}

// Represents a period of time in which a program was executing in a particular context.
//
// Corresponds to `Span` in the `tracing` crate.
type Span struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An Id that uniquely identifies it in relation to other spans.
	Id *SpanId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier for metadata describing static characteristics of all spans originating
	// from that callsite, such as its name, source code location, verbosity level, and
	// the names of its fields.
	MetadataId *MetaId `protobuf:"bytes,2,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	// User-defined key-value pairs of arbitrary data that describe the context the span represents,
	Fields []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Timestamp for the span.
	At            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *Span) GetId() *SpanId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Span) GetMetadataId() *MetaId {
	if x != nil {
		return x.MetadataId
	}
	return nil
}

func (x *Span) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Span) GetAt() *timestamp.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// Any new metadata that was registered since the last update.
type RegisterMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new metadata that was registered since the last update.
	Metadata      []*RegisterMetadata_NewMetadata `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMetadata) Reset() {
	*x = RegisterMetadata{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMetadata) ProtoMessage() {}

func (x *RegisterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMetadata.ProtoReflect.Descriptor instead.
func (*RegisterMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterMetadata) GetMetadata() []*RegisterMetadata_NewMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata associated with a span or event.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the span or event.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Describes the part of the system where the span or event that this
	// metadata describes occurred.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// The path to the Rust module where the span occurred.
	ModulePath string `protobuf:"bytes,3,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	// The Rust source location associated with the span or event.
	Location *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// Indicates whether metadata is associated with a span or with an event.
	Kind Metadata_Kind `protobuf:"varint,5,opt,name=kind,proto3,enum=rs.tokio.console.common.Metadata_Kind" json:"kind,omitempty"`
	// Describes the level of verbosity of a span or event.
	Level Metadata_Level `protobuf:"varint,6,opt,name=level,proto3,enum=rs.tokio.console.common.Metadata_Level" json:"level,omitempty"`
	// The names of the key-value fields attached to the
	// span or event this metadata is associated with.
	FieldNames    []string `protobuf:"bytes,7,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Metadata) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *Metadata) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Metadata) GetKind() Metadata_Kind {
	if x != nil {
		return x.Kind
	}
	return Metadata_SPAN
}

func (x *Metadata) GetLevel() Metadata_Level {
	if x != nil {
		return x.Level
	}
	return Metadata_ERROR
}

func (x *Metadata) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

// Contains stats about objects that can be polled. Currently these can be:
// - tasks that have been spawned
// - async operations on resources that are performed within the context of a task
type PollStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The total number of times this object has been polled.
	Polls uint64 `protobuf:"varint,1,opt,name=polls,proto3" json:"polls,omitempty"`
	// The timestamp of the first time this object was polled.
	//
	// If this is `None`, the object has not yet been polled.
	//
	// Subtracting this timestamp from `created_at` can be used to calculate the
	// time to first poll for this object, a measurement of executor latency.
	FirstPoll *timestamp.Timestamp `protobuf:"bytes,3,opt,name=first_poll,json=firstPoll,proto3,oneof" json:"first_poll,omitempty"`
	// The timestamp of the most recent time this objects's poll method was invoked.
	//
	// If this is `None`, the object has not yet been polled.
	//
	// If the object has only been polled a single time, then this value may be
	// equal to the `first_poll` timestamp.
	LastPollStarted *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_poll_started,json=lastPollStarted,proto3,oneof" json:"last_poll_started,omitempty"`
	// The timestamp of the most recent time this objects's poll method finished execution.
	//
	// If this is `None`, the object has not yet been polled or is currently being polled.
	//
	// If the object does not exist anymore, then this is the time the final invocation of
	// its poll method has completed.
	LastPollEnded *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_poll_ended,json=lastPollEnded,proto3,oneof" json:"last_poll_ended,omitempty"`
	// The total duration this object was being *actively polled*, summed across
	// all polls.
	//
	// Note that this includes only polls that have completed, and does not
	// reflect any in-progress polls. Subtracting `busy_time` from the
	// total lifetime of the polled object results in the amount of time it
	// has spent *waiting* to be polled (including the `scheduled_time` value
	// from `TaskStats`, if this is a task).
	BusyTime      *duration.Duration `protobuf:"bytes,6,opt,name=busy_time,json=busyTime,proto3" json:"busy_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollStats) Reset() {
	*x = PollStats{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollStats) ProtoMessage() {}

func (x *PollStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollStats.ProtoReflect.Descriptor instead.
func (*PollStats) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *PollStats) GetPolls() uint64 {
	if x != nil {
		return x.Polls
	}
	return 0
}

func (x *PollStats) GetFirstPoll() *timestamp.Timestamp {
	if x != nil {
		return x.FirstPoll
	}
	return nil
}

func (x *PollStats) GetLastPollStarted() *timestamp.Timestamp {
	if x != nil {
		return x.LastPollStarted
	}
	return nil
}

func (x *PollStats) GetLastPollEnded() *timestamp.Timestamp {
	if x != nil {
		return x.LastPollEnded
	}
	return nil
}

func (x *PollStats) GetBusyTime() *duration.Duration {
	if x != nil {
		return x.BusyTime
	}
	return nil
}

// State attributes of an entity. These are dependent on the type of the entity.
//
// For example, a timer resource will have a duration, while a semaphore resource may
// have a permit count. Likewise, the async ops of a semaphore may have attributes
// indicating how many permits they are trying to acquire vs how many are acquired.
// These values may change over time. Therefore, they live in the runtime stats rather
// than the static data describing the entity.
type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key-value pair for the attribute
	Field *Field `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Some values carry a unit of measurement. For example, a duration
	// carries an associated unit of time, such as "ms" for milliseconds.
	Unit          *string `protobuf:"bytes,2,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *Attribute) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Attribute) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

// One metadata element registered since the last update.
type RegisterMetadata_NewMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for `metadata`.
	Id *MetaId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The metadata payload.
	Metadata      *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMetadata_NewMetadata) Reset() {
	*x = RegisterMetadata_NewMetadata{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMetadata_NewMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMetadata_NewMetadata) ProtoMessage() {}

func (x *RegisterMetadata_NewMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMetadata_NewMetadata.ProtoReflect.Descriptor instead.
func (*RegisterMetadata_NewMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RegisterMetadata_NewMetadata) GetId() *MetaId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RegisterMetadata_NewMetadata) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x17rs.tokio.console.common\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xac\x01\n" +
	"\bLocation\x12\x17\n" +
	"\x04file\x18\x01 \x01(\tH\x00R\x04file\x88\x01\x01\x12$\n" +
	"\vmodule_path\x18\x02 \x01(\tH\x01R\n" +
	"modulePath\x88\x01\x01\x12\x17\n" +
	"\x04line\x18\x03 \x01(\rH\x02R\x04line\x88\x01\x01\x12\x1b\n" +
	"\x06column\x18\x04 \x01(\rH\x03R\x06column\x88\x01\x01B\a\n" +
	"\x05_fileB\x0e\n" +
	"\f_module_pathB\a\n" +
	"\x05_lineB\t\n" +
	"\a_column\"\x18\n" +
	"\x06MetaId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x18\n" +
	"\x06SpanId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xa1\x02\n" +
	"\x05Field\x12\x1b\n" +
	"\bstr_name\x18\x01 \x01(\tH\x00R\astrName\x12\x1b\n" +
	"\bname_idx\x18\x02 \x01(\x04H\x00R\anameIdx\x12\x1d\n" +
	"\tdebug_val\x18\x03 \x01(\tH\x01R\bdebugVal\x12\x19\n" +
	"\astr_val\x18\x04 \x01(\tH\x01R\x06strVal\x12\x19\n" +
	"\au64_val\x18\x05 \x01(\x04H\x01R\x06u64Val\x12\x19\n" +
	"\ai64_val\x18\x06 \x01(\x12H\x01R\x06i64Val\x12\x1b\n" +
	"\bbool_val\x18\a \x01(\bH\x01R\aboolVal\x12@\n" +
	"\vmetadata_id\x18\b \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\n" +
	"metadataIdB\x06\n" +
	"\x04nameB\a\n" +
	"\x05value\"\xdd\x01\n" +
	"\x04Span\x12/\n" +
	"\x02id\x18\x01 \x01(\v2\x1f.rs.tokio.console.common.SpanIdR\x02id\x12@\n" +
	"\vmetadata_id\x18\x02 \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\n" +
	"metadataId\x126\n" +
	"\x06fields\x18\x03 \x03(\v2\x1e.rs.tokio.console.common.FieldR\x06fields\x12*\n" +
	"\x02at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xe4\x01\n" +
	"\x10RegisterMetadata\x12Q\n" +
	"\bmetadata\x18\x01 \x03(\v25.rs.tokio.console.common.RegisterMetadata.NewMetadataR\bmetadata\x1a}\n" +
	"\vNewMetadata\x12/\n" +
	"\x02id\x18\x01 \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\x02id\x12=\n" +
	"\bmetadata\x18\x02 \x01(\v2!.rs.tokio.console.common.MetadataR\bmetadata\"\x8d\x03\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1f\n" +
	"\vmodule_path\x18\x03 \x01(\tR\n" +
	"modulePath\x12=\n" +
	"\blocation\x18\x04 \x01(\v2!.rs.tokio.console.common.LocationR\blocation\x12:\n" +
	"\x04kind\x18\x05 \x01(\x0e2&.rs.tokio.console.common.Metadata.KindR\x04kind\x12=\n" +
	"\x05level\x18\x06 \x01(\x0e2'.rs.tokio.console.common.Metadata.LevelR\x05level\x12\x1f\n" +
	"\vfield_names\x18\a \x03(\tR\n" +
	"fieldNames\"\x1b\n" +
	"\x04Kind\x12\b\n" +
	"\x04SPAN\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\"<\n" +
	"\x05Level\x12\t\n" +
	"\x05ERROR\x10\x00\x12\b\n" +
	"\x04WARN\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\t\n" +
	"\x05DEBUG\x10\x03\x12\t\n" +
	"\x05TRACE\x10\x04\"\xe8\x02\n" +
	"\tPollStats\x12\x14\n" +
	"\x05polls\x18\x01 \x01(\x04R\x05polls\x12>\n" +
	"\n" +
	"first_poll\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tfirstPoll\x88\x01\x01\x12K\n" +
	"\x11last_poll_started\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0flastPollStarted\x88\x01\x01\x12G\n" +
	"\x0flast_poll_ended\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\rlastPollEnded\x88\x01\x01\x126\n" +
	"\tbusy_time\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\bbusyTimeB\r\n" +
	"\v_first_pollB\x14\n" +
	"\x12_last_poll_startedB\x12\n" +
	"\x10_last_poll_ended\"c\n" +
	"\tAttribute\x124\n" +
	"\x05field\x18\x01 \x01(\v2\x1e.rs.tokio.console.common.FieldR\x05field\x12\x17\n" +
	"\x04unit\x18\x02 \x01(\tH\x00R\x04unit\x88\x01\x01B\a\n" +
	"\x05_unitb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_goTypes = []any{
	(Metadata_Kind)(0),                   // 0: rs.tokio.console.common.Metadata.Kind
	(Metadata_Level)(0),                  // 1: rs.tokio.console.common.Metadata.Level
	(*Id)(nil),                           // 2: rs.tokio.console.common.Id
	(*Location)(nil),                     // 3: rs.tokio.console.common.Location
	(*MetaId)(nil),                       // 4: rs.tokio.console.common.MetaId
	(*SpanId)(nil),                       // 5: rs.tokio.console.common.SpanId
	(*Field)(nil),                        // 6: rs.tokio.console.common.Field
	(*Span)(nil),                         // 7: rs.tokio.console.common.Span
	(*RegisterMetadata)(nil),             // 8: rs.tokio.console.common.RegisterMetadata
	(*Metadata)(nil),                     // 9: rs.tokio.console.common.Metadata
	(*PollStats)(nil),                    // 10: rs.tokio.console.common.PollStats
	(*Attribute)(nil),                    // 11: rs.tokio.console.common.Attribute
	(*RegisterMetadata_NewMetadata)(nil), // 12: rs.tokio.console.common.RegisterMetadata.NewMetadata
	(*timestamp.Timestamp)(nil),          // 13: google.protobuf.Timestamp
	(*duration.Duration)(nil),            // 14: google.protobuf.Duration
}
var file_common_proto_depIdxs = []int32{
	4,  // 0: rs.tokio.console.common.Field.metadata_id:type_name -> rs.tokio.console.common.MetaId
	5,  // 1: rs.tokio.console.common.Span.id:type_name -> rs.tokio.console.common.SpanId
	4,  // 2: rs.tokio.console.common.Span.metadata_id:type_name -> rs.tokio.console.common.MetaId
	6,  // 3: rs.tokio.console.common.Span.fields:type_name -> rs.tokio.console.common.Field
	13, // 4: rs.tokio.console.common.Span.at:type_name -> google.protobuf.Timestamp
	12, // 5: rs.tokio.console.common.RegisterMetadata.metadata:type_name -> rs.tokio.console.common.RegisterMetadata.NewMetadata
	3,  // 6: rs.tokio.console.common.Metadata.location:type_name -> rs.tokio.console.common.Location
	0,  // 7: rs.tokio.console.common.Metadata.kind:type_name -> rs.tokio.console.common.Metadata.Kind
	1,  // 8: rs.tokio.console.common.Metadata.level:type_name -> rs.tokio.console.common.Metadata.Level
	13, // 9: rs.tokio.console.common.PollStats.first_poll:type_name -> google.protobuf.Timestamp
	13, // 10: rs.tokio.console.common.PollStats.last_poll_started:type_name -> google.protobuf.Timestamp
	13, // 11: rs.tokio.console.common.PollStats.last_poll_ended:type_name -> google.protobuf.Timestamp
	14, // 12: rs.tokio.console.common.PollStats.busy_time:type_name -> google.protobuf.Duration
	6,  // 13: rs.tokio.console.common.Attribute.field:type_name -> rs.tokio.console.common.Field
	4,  // 14: rs.tokio.console.common.RegisterMetadata.NewMetadata.id:type_name -> rs.tokio.console.common.MetaId
	9,  // 15: rs.tokio.console.common.RegisterMetadata.NewMetadata.metadata:type_name -> rs.tokio.console.common.Metadata
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_proto_msgTypes[4].OneofWrappers = []any{
		(*Field_StrName)(nil),
		(*Field_NameIdx)(nil),
		(*Field_DebugVal)(nil),
		(*Field_StrVal)(nil),
		(*Field_U64Val)(nil),
		(*Field_I64Val)(nil),
		(*Field_BoolVal)(nil),
	}
	file_common_proto_msgTypes[8].OneofWrappers = []any{}
	file_common_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
