// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: tasks.proto

package tasks

import (
	common "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/common"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The category of task this task belongs to.
type Task_Kind int32

const (
	// A task spawned using a runtime's standard asynchronous task spawning
	// operation (such as `tokio::task::spawn`).
	Task_SPAWN Task_Kind = 0
	// A task spawned via a runtime's blocking task spawning operation
	// (such as `tokio::task::spawn_blocking`).
	Task_BLOCKING Task_Kind = 1
)

// Enum value maps for Task_Kind.
var (
	Task_Kind_name = map[int32]string{
		0: "SPAWN",
		1: "BLOCKING",
	}
	Task_Kind_value = map[string]int32{
		"SPAWN":    0,
		"BLOCKING": 1,
	}
)

func (x Task_Kind) Enum() *Task_Kind {
	p := new(Task_Kind)
	*p = x
	return p
}

func (x Task_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_proto_enumTypes[0].Descriptor()
}

func (Task_Kind) Type() protoreflect.EnumType {
	return &file_tasks_proto_enumTypes[0]
}

func (x Task_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_Kind.Descriptor instead.
func (Task_Kind) EnumDescriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{2, 0}
}

// A task state update.
//
// Each `TaskUpdate` contains any task data that has changed since the last
// update. This includes:
// - any new tasks that were spawned since the last update
// - the current stats for any task whose stats changed since the last update
type TaskUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of new tasks that were spawned since the last `TaskUpdate` was
	// sent.
	//
	// If this is empty, no new tasks were spawned.
	NewTasks []*Task `protobuf:"bytes,1,rep,name=new_tasks,json=newTasks,proto3" json:"new_tasks,omitempty"`
	// Any task stats that have changed since the last update.
	//
	// This is a map of task IDs (64-bit unsigned integers) to task stats. If a
	// task's ID is not included in this map, then its stats have *not* changed
	// since the last `TaskUpdate` in which they were present. If a task's ID
	// *is* included in this map, the corresponding value represents a complete
	// snapshot of that task's stats at in the current time window.
	StatsUpdate map[uint64]*Stats `protobuf:"bytes,3,rep,name=stats_update,json=statsUpdate,proto3" json:"stats_update,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A count of how many task events (e.g. polls, spawns, etc) were not
	// recorded because the application's event buffer was at capacity.
	//
	// If everything is working normally, this should be 0. If it is greater
	// than 0, that may indicate that some data is missing from this update, and
	// it may be necessary to increase the number of events buffered by the
	// application to ensure that data loss is avoided.
	//
	// If the application's instrumentation ensures reliable delivery of events,
	// this will always be 0.
	DroppedEvents uint64 `protobuf:"varint,4,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *TaskUpdate) GetNewTasks() []*Task {
	if x != nil {
		return x.NewTasks
	}
	return nil
}

func (x *TaskUpdate) GetStatsUpdate() map[uint64]*Stats {
	if x != nil {
		return x.StatsUpdate
	}
	return nil
}

func (x *TaskUpdate) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

// A task details update
type TaskDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task's ID which the details belong to.
	TaskId *common.Id `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The timestamp for when the update to the task took place.
	Now *timestamp.Timestamp `protobuf:"bytes,2,opt,name=now,proto3" json:"now,omitempty"`
	// A histogram of task poll durations.
	//
	// This is either:
	//   - the raw binary representation of a HdrHistogram.rs `Histogram`
	//     serialized to binary in the V2 format (legacy)
	//   - a binary histogram plus details on outliers (current)
	//
	// Types that are valid to be assigned to PollTimesHistogram:
	//
	//	*TaskDetails_LegacyHistogram
	//	*TaskDetails_Histogram
	PollTimesHistogram isTaskDetails_PollTimesHistogram `protobuf_oneof:"poll_times_histogram"`
	// A histogram of task scheduled durations.
	//
	// The scheduled duration is the time a task spends between being
	// woken and when it is next polled.
	ScheduledTimesHistogram *DurationHistogram `protobuf:"bytes,5,opt,name=scheduled_times_histogram,json=scheduledTimesHistogram,proto3" json:"scheduled_times_histogram,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TaskDetails) Reset() {
	*x = TaskDetails{}
	mi := &file_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetails) ProtoMessage() {}

func (x *TaskDetails) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetails.ProtoReflect.Descriptor instead.
func (*TaskDetails) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *TaskDetails) GetTaskId() *common.Id {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TaskDetails) GetNow() *timestamp.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *TaskDetails) GetPollTimesHistogram() isTaskDetails_PollTimesHistogram {
	if x != nil {
		return x.PollTimesHistogram
	}
	return nil
}

func (x *TaskDetails) GetLegacyHistogram() []byte {
	if x != nil {
		if x, ok := x.PollTimesHistogram.(*TaskDetails_LegacyHistogram); ok {
			return x.LegacyHistogram
		}
	}
	return nil
}

func (x *TaskDetails) GetHistogram() *DurationHistogram {
	if x != nil {
		if x, ok := x.PollTimesHistogram.(*TaskDetails_Histogram); ok {
			return x.Histogram
		}
	}
	return nil
}

func (x *TaskDetails) GetScheduledTimesHistogram() *DurationHistogram {
	if x != nil {
		return x.ScheduledTimesHistogram
	}
	return nil
}

type isTaskDetails_PollTimesHistogram interface {
	isTaskDetails_PollTimesHistogram()
}

type TaskDetails_LegacyHistogram struct {
	// HdrHistogram.rs `Histogram` serialized to binary in the V2 format
	LegacyHistogram []byte `protobuf:"bytes,3,opt,name=legacy_histogram,json=legacyHistogram,proto3,oneof"`
}

type TaskDetails_Histogram struct {
	// A histogram plus additional data.
	Histogram *DurationHistogram `protobuf:"bytes,4,opt,name=histogram,proto3,oneof"`
}

func (*TaskDetails_LegacyHistogram) isTaskDetails_PollTimesHistogram() {}

func (*TaskDetails_Histogram) isTaskDetails_PollTimesHistogram() {}

// Data recorded when a new task is spawned.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task's ID.
	//
	// This uniquely identifies this task across all *currently live* tasks.
	// When the task's stats change, or when the task completes, it will be
	// identified by this ID; if the client requires additional information
	// included in the `Task` message, it should store that data and access it
	// by ID.
	Id *common.Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The numeric ID of the task's `Metadata`.
	//
	// This identifies the `Metadata` that describes the `tracing` span
	// corresponding to this task. The metadata for this ID will have been sent
	// in a prior `RegisterMetadata` message.
	Metadata *common.MetaId `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The category of task this task belongs to.
	Kind Task_Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=rs.tokio.console.tasks.Task_Kind" json:"kind,omitempty"`
	// A list of `Field` objects attached to this task.
	Fields []*common.Field `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	// An ordered list of span IDs corresponding to the `tracing` span context
	// in which this task was spawned.
	//
	// The first span ID in this list is the immediate parent, followed by that
	// span's parent, and so on. The final ID is the root span of the current
	// trace.
	//
	// If this is empty, there were *no* active spans when the task was spawned.
	//
	// These IDs may correspond to `tracing` spans which are *not* tasks, if
	// additional trace data is being collected.
	Parents []*common.SpanId `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	// The location in code where the task was spawned.
	Location      *common.Location `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() *common.Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Task) GetMetadata() *common.MetaId {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetKind() Task_Kind {
	if x != nil {
		return x.Kind
	}
	return Task_SPAWN
}

func (x *Task) GetFields() []*common.Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Task) GetParents() []*common.SpanId {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Task) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Task performance statistics.
type Stats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of when the task was spawned.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of when the task was dropped.
	DroppedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=dropped_at,json=droppedAt,proto3" json:"dropped_at,omitempty"`
	// The total number of times this task has been woken over its lifetime.
	Wakes uint64 `protobuf:"varint,3,opt,name=wakes,proto3" json:"wakes,omitempty"`
	// The total number of times this task's waker has been cloned.
	WakerClones uint64 `protobuf:"varint,4,opt,name=waker_clones,json=wakerClones,proto3" json:"waker_clones,omitempty"`
	// The total number of times this task's waker has been dropped.
	WakerDrops uint64 `protobuf:"varint,5,opt,name=waker_drops,json=wakerDrops,proto3" json:"waker_drops,omitempty"`
	// The timestamp of the most recent time this task has been woken.
	//
	// If this is `None`, the task has not yet been woken.
	LastWake *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_wake,json=lastWake,proto3,oneof" json:"last_wake,omitempty"`
	// Contains task poll statistics.
	PollStats *common.PollStats `protobuf:"bytes,7,opt,name=poll_stats,json=pollStats,proto3" json:"poll_stats,omitempty"`
	// The total number of times this task has woken itself.
	SelfWakes uint64 `protobuf:"varint,8,opt,name=self_wakes,json=selfWakes,proto3" json:"self_wakes,omitempty"`
	// The total duration this task was scheduled prior to being polled, summed
	// across all poll cycles.
	//
	// Note that this includes only polls that have started, and does not
	// reflect any scheduled state where the task hasn't yet been polled.
	// Subtracting both `busy_time` (from the task's `PollStats`) and
	// `scheduled_time` from the total lifetime of the task results in the
	// amount of time it spent unable to progress because it was waiting on
	// some resource.
	ScheduledTime *duration.Duration `protobuf:"bytes,9,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *Stats) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stats) GetDroppedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DroppedAt
	}
	return nil
}

func (x *Stats) GetWakes() uint64 {
	if x != nil {
		return x.Wakes
	}
	return 0
}

func (x *Stats) GetWakerClones() uint64 {
	if x != nil {
		return x.WakerClones
	}
	return 0
}

func (x *Stats) GetWakerDrops() uint64 {
	if x != nil {
		return x.WakerDrops
	}
	return 0
}

func (x *Stats) GetLastWake() *timestamp.Timestamp {
	if x != nil {
		return x.LastWake
	}
	return nil
}

func (x *Stats) GetPollStats() *common.PollStats {
	if x != nil {
		return x.PollStats
	}
	return nil
}

func (x *Stats) GetSelfWakes() uint64 {
	if x != nil {
		return x.SelfWakes
	}
	return 0
}

func (x *Stats) GetScheduledTime() *duration.Duration {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

type DurationHistogram struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HdrHistogram.rs `Histogram` serialized to binary in the V2 format
	RawHistogram []byte `protobuf:"bytes,1,opt,name=raw_histogram,json=rawHistogram,proto3" json:"raw_histogram,omitempty"`
	// The histogram's maximum value.
	MaxValue uint64 `protobuf:"varint,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	// The number of outliers which have exceeded the histogram's maximum value.
	HighOutliers uint64 `protobuf:"varint,3,opt,name=high_outliers,json=highOutliers,proto3" json:"high_outliers,omitempty"`
	// The highest recorded outlier. This is only present if `high_outliers` is
	// greater than zero.
	HighestOutlier *uint64 `protobuf:"varint,4,opt,name=highest_outlier,json=highestOutlier,proto3,oneof" json:"highest_outlier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DurationHistogram) Reset() {
	*x = DurationHistogram{}
	mi := &file_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationHistogram) ProtoMessage() {}

func (x *DurationHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationHistogram.ProtoReflect.Descriptor instead.
func (*DurationHistogram) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *DurationHistogram) GetRawHistogram() []byte {
	if x != nil {
		return x.RawHistogram
	}
	return nil
}

func (x *DurationHistogram) GetMaxValue() uint64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *DurationHistogram) GetHighOutliers() uint64 {
	if x != nil {
		return x.HighOutliers
	}
	return 0
}

func (x *DurationHistogram) GetHighestOutlier() uint64 {
	if x != nil && x.HighestOutlier != nil {
		return *x.HighestOutlier
	}
	return 0
}

var File_tasks_proto protoreflect.FileDescriptor

const file_tasks_proto_rawDesc = "" +
	"\n" +
	"\vtasks.proto\x12\x16rs.tokio.console.tasks\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\fcommon.proto\"\xa5\x02\n" +
	"\n" +
	"TaskUpdate\x129\n" +
	"\tnew_tasks\x18\x01 \x03(\v2\x1c.rs.tokio.console.tasks.TaskR\bnewTasks\x12V\n" +
	"\fstats_update\x18\x03 \x03(\v23.rs.tokio.console.tasks.TaskUpdate.StatsUpdateEntryR\vstatsUpdate\x12%\n" +
	"\x0edropped_events\x18\x04 \x01(\x04R\rdroppedEvents\x1a]\n" +
	"\x10StatsUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.rs.tokio.console.tasks.StatsR\x05value:\x028\x01\"\xe8\x02\n" +
	"\vTaskDetails\x124\n" +
	"\atask_id\x18\x01 \x01(\v2\x1b.rs.tokio.console.common.IdR\x06taskId\x12,\n" +
	"\x03now\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\x12+\n" +
	"\x10legacy_histogram\x18\x03 \x01(\fH\x00R\x0flegacyHistogram\x12I\n" +
	"\thistogram\x18\x04 \x01(\v2).rs.tokio.console.tasks.DurationHistogramH\x00R\thistogram\x12e\n" +
	"\x19scheduled_times_histogram\x18\x05 \x01(\v2).rs.tokio.console.tasks.DurationHistogramR\x17scheduledTimesHistogramB\x16\n" +
	"\x14poll_times_histogram\"\xfa\x02\n" +
	"\x04Task\x12+\n" +
	"\x02id\x18\x01 \x01(\v2\x1b.rs.tokio.console.common.IdR\x02id\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\bmetadata\x125\n" +
	"\x04kind\x18\x03 \x01(\x0e2!.rs.tokio.console.tasks.Task.KindR\x04kind\x126\n" +
	"\x06fields\x18\x04 \x03(\v2\x1e.rs.tokio.console.common.FieldR\x06fields\x129\n" +
	"\aparents\x18\x05 \x03(\v2\x1f.rs.tokio.console.common.SpanIdR\aparents\x12=\n" +
	"\blocation\x18\x06 \x01(\v2!.rs.tokio.console.common.LocationR\blocation\"\x1f\n" +
	"\x04Kind\x12\t\n" +
	"\x05SPAWN\x10\x00\x12\f\n" +
	"\bBLOCKING\x10\x01\"\xc7\x03\n" +
	"\x05Stats\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"dropped_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdroppedAt\x12\x14\n" +
	"\x05wakes\x18\x03 \x01(\x04R\x05wakes\x12!\n" +
	"\fwaker_clones\x18\x04 \x01(\x04R\vwakerClones\x12\x1f\n" +
	"\vwaker_drops\x18\x05 \x01(\x04R\n" +
	"wakerDrops\x12<\n" +
	"\tlast_wake\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\blastWake\x88\x01\x01\x12A\n" +
	"\n" +
	"poll_stats\x18\a \x01(\v2\".rs.tokio.console.common.PollStatsR\tpollStats\x12\x1d\n" +
	"\n" +
	"self_wakes\x18\b \x01(\x04R\tselfWakes\x12@\n" +
	"\x0escheduled_time\x18\t \x01(\v2\x19.google.protobuf.DurationR\rscheduledTimeB\f\n" +
	"\n" +
	"_last_wake\"\xbc\x01\n" +
	"\x11DurationHistogram\x12#\n" +
	"\rraw_histogram\x18\x01 \x01(\fR\frawHistogram\x12\x1b\n" +
	"\tmax_value\x18\x02 \x01(\x04R\bmaxValue\x12#\n" +
	"\rhigh_outliers\x18\x03 \x01(\x04R\fhighOutliers\x12,\n" +
	"\x0fhighest_outlier\x18\x04 \x01(\x04H\x00R\x0ehighestOutlier\x88\x01\x01B\x12\n" +
	"\x10_highest_outlierb\x06proto3"

var (
	file_tasks_proto_rawDescOnce sync.Once
	file_tasks_proto_rawDescData []byte
)

func file_tasks_proto_rawDescGZIP() []byte {
	file_tasks_proto_rawDescOnce.Do(func() {
		file_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_proto_rawDesc), len(file_tasks_proto_rawDesc)))
	})
	return file_tasks_proto_rawDescData
}

var file_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tasks_proto_goTypes = []any{
	(Task_Kind)(0),              // 0: rs.tokio.console.tasks.Task.Kind
	(*TaskUpdate)(nil),          // 1: rs.tokio.console.tasks.TaskUpdate
	(*TaskDetails)(nil),         // 2: rs.tokio.console.tasks.TaskDetails
	(*Task)(nil),                // 3: rs.tokio.console.tasks.Task
	(*Stats)(nil),               // 4: rs.tokio.console.tasks.Stats
	(*DurationHistogram)(nil),   // 5: rs.tokio.console.tasks.DurationHistogram
	nil,                         // 6: rs.tokio.console.tasks.TaskUpdate.StatsUpdateEntry
	(*common.Id)(nil),           // 7: rs.tokio.console.common.Id
	(*timestamp.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*common.MetaId)(nil),       // 9: rs.tokio.console.common.MetaId
	(*common.Field)(nil),        // 10: rs.tokio.console.common.Field
	(*common.SpanId)(nil),       // 11: rs.tokio.console.common.SpanId
	(*common.Location)(nil),     // 12: rs.tokio.console.common.Location
	(*common.PollStats)(nil),    // 13: rs.tokio.console.common.PollStats
	(*duration.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_tasks_proto_depIdxs = []int32{
	3,  // 0: rs.tokio.console.tasks.TaskUpdate.new_tasks:type_name -> rs.tokio.console.tasks.Task
	6,  // 1: rs.tokio.console.tasks.TaskUpdate.stats_update:type_name -> rs.tokio.console.tasks.TaskUpdate.StatsUpdateEntry
	7,  // 2: rs.tokio.console.tasks.TaskDetails.task_id:type_name -> rs.tokio.console.common.Id
	8,  // 3: rs.tokio.console.tasks.TaskDetails.now:type_name -> google.protobuf.Timestamp
	5,  // 4: rs.tokio.console.tasks.TaskDetails.histogram:type_name -> rs.tokio.console.tasks.DurationHistogram
	5,  // 5: rs.tokio.console.tasks.TaskDetails.scheduled_times_histogram:type_name -> rs.tokio.console.tasks.DurationHistogram
	7,  // 6: rs.tokio.console.tasks.Task.id:type_name -> rs.tokio.console.common.Id
	9,  // 7: rs.tokio.console.tasks.Task.metadata:type_name -> rs.tokio.console.common.MetaId
	0,  // 8: rs.tokio.console.tasks.Task.kind:type_name -> rs.tokio.console.tasks.Task.Kind
	10, // 9: rs.tokio.console.tasks.Task.fields:type_name -> rs.tokio.console.common.Field
	11, // 10: rs.tokio.console.tasks.Task.parents:type_name -> rs.tokio.console.common.SpanId
	12, // 11: rs.tokio.console.tasks.Task.location:type_name -> rs.tokio.console.common.Location
	8,  // 12: rs.tokio.console.tasks.Stats.created_at:type_name -> google.protobuf.Timestamp
	8,  // 13: rs.tokio.console.tasks.Stats.dropped_at:type_name -> google.protobuf.Timestamp
	8,  // 14: rs.tokio.console.tasks.Stats.last_wake:type_name -> google.protobuf.Timestamp
	13, // 15: rs.tokio.console.tasks.Stats.poll_stats:type_name -> rs.tokio.console.common.PollStats
	14, // 16: rs.tokio.console.tasks.Stats.scheduled_time:type_name -> google.protobuf.Duration
	4,  // 17: rs.tokio.console.tasks.TaskUpdate.StatsUpdateEntry.value:type_name -> rs.tokio.console.tasks.Stats
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_tasks_proto_init() }
func file_tasks_proto_init() {
	if File_tasks_proto != nil {
		return
	}
	file_tasks_proto_msgTypes[1].OneofWrappers = []any{
		(*TaskDetails_LegacyHistogram)(nil),
		(*TaskDetails_Histogram)(nil),
	}
	file_tasks_proto_msgTypes[3].OneofWrappers = []any{}
	file_tasks_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_proto_rawDesc), len(file_tasks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tasks_proto_goTypes,
		DependencyIndexes: file_tasks_proto_depIdxs,
		EnumInfos:         file_tasks_proto_enumTypes,
		MessageInfos:      file_tasks_proto_msgTypes,
	}.Build()
	File_tasks_proto = out.File
	file_tasks_proto_goTypes = nil
	file_tasks_proto_depIdxs = nil
}
