// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: resources.proto

package resources

import (
	common "github.com/briheet/sen/internal/adapters/rust/runtime/console/proto/common"
	_ "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// `Known` collects the kinds of resources that are known in this version of the API.
type Resource_Kind_Known int32

const (
	// `TIMER` signals that this is a timer resource, e.g. waiting for a sleep to finish.
	Resource_Kind_TIMER Resource_Kind_Known = 0
)

// Enum value maps for Resource_Kind_Known.
var (
	Resource_Kind_Known_name = map[int32]string{
		0: "TIMER",
	}
	Resource_Kind_Known_value = map[string]int32{
		"TIMER": 0,
	}
)

func (x Resource_Kind_Known) Enum() *Resource_Kind_Known {
	p := new(Resource_Kind_Known)
	*p = x
	return p
}

func (x Resource_Kind_Known) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resource_Kind_Known) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_proto_enumTypes[0].Descriptor()
}

func (Resource_Kind_Known) Type() protoreflect.EnumType {
	return &file_resources_proto_enumTypes[0]
}

func (x Resource_Kind_Known) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resource_Kind_Known.Descriptor instead.
func (Resource_Kind_Known) EnumDescriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{1, 0, 0}
}

// A resource state update.
//
// Each `ResourceUpdate` contains any resource data that has changed since the last
// update. This includes:
// - any new resources that were created since the last update
// - the current stats for any resource whose stats changed since the last update
// - any new poll ops that have been invoked on a resource
type ResourceUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of new resources that were created since the last `ResourceUpdate` was
	// sent.
	NewResources []*Resource `protobuf:"bytes,1,rep,name=new_resources,json=newResources,proto3" json:"new_resources,omitempty"`
	// Any resource stats that have changed since the last update.
	StatsUpdate map[uint64]*Stats `protobuf:"bytes,2,rep,name=stats_update,json=statsUpdate,proto3" json:"stats_update,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A list of all new poll ops that have been invoked on resources since the last update.
	NewPollOps []*PollOp `protobuf:"bytes,3,rep,name=new_poll_ops,json=newPollOps,proto3" json:"new_poll_ops,omitempty"`
	// A count of how many resource events (e.g. polls, creation, etc) were not
	// recorded because the application's event buffer was at capacity.
	//
	// If everything is working normally, this should be 0. If it is greater
	// than 0, that may indicate that some data is missing from this update, and
	// it may be necessary to increase the number of events buffered by the
	// application to ensure that data loss is avoided.
	//
	// If the application's instrumentation ensures reliable delivery of events,
	// this will always be 0.
	DroppedEvents uint64 `protobuf:"varint,4,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUpdate) Reset() {
	*x = ResourceUpdate{}
	mi := &file_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUpdate) ProtoMessage() {}

func (x *ResourceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUpdate.ProtoReflect.Descriptor instead.
func (*ResourceUpdate) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceUpdate) GetNewResources() []*Resource {
	if x != nil {
		return x.NewResources
	}
	return nil
}

func (x *ResourceUpdate) GetStatsUpdate() map[uint64]*Stats {
	if x != nil {
		return x.StatsUpdate
	}
	return nil
}

func (x *ResourceUpdate) GetNewPollOps() []*PollOp {
	if x != nil {
		return x.NewPollOps
	}
	return nil
}

func (x *ResourceUpdate) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

// Static data recorded when a new resource is created.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resources's ID.
	//
	// This uniquely identifies this resource across all *currently live*
	// resources. This is also the primary way any operations on a resource
	// are associated with it
	Id *common.Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The numeric ID of the resources's `Metadata`.
	Metadata *common.MetaId `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The resources's concrete rust type.
	ConcreteType string `protobuf:"bytes,3,opt,name=concrete_type,json=concreteType,proto3" json:"concrete_type,omitempty"`
	// The kind of resource (e.g timer, mutex)
	Kind *Resource_Kind `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// The location in code where the resource was created.
	Location *common.Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// The ID of the parent resource.
	ParentResourceId *common.Id `protobuf:"bytes,6,opt,name=parent_resource_id,json=parentResourceId,proto3" json:"parent_resource_id,omitempty"`
	// Is the resource an internal component of another resource?
	//
	// For example, a `tokio::time::Interval` resource might contain a
	// `tokio::time::Sleep` resource internally.
	IsInternal    bool `protobuf:"varint,7,opt,name=is_internal,json=isInternal,proto3" json:"is_internal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() *common.Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Resource) GetMetadata() *common.MetaId {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetConcreteType() string {
	if x != nil {
		return x.ConcreteType
	}
	return ""
}

func (x *Resource) GetKind() *Resource_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Resource) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Resource) GetParentResourceId() *common.Id {
	if x != nil {
		return x.ParentResourceId
	}
	return nil
}

func (x *Resource) GetIsInternal() bool {
	if x != nil {
		return x.IsInternal
	}
	return false
}

// Task runtime stats of a resource.
type Stats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of when the resource was created.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of when the resource was dropped.
	DroppedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=dropped_at,json=droppedAt,proto3" json:"dropped_at,omitempty"`
	// State attributes of the resource. These are dependent on the type of the resource.
	// For example, a timer resource will have a duration while a semaphore resource may
	// have permits as an attribute. These values may change over time as the state of
	// the resource changes. Therefore, they live in the runtime stats rather than the
	// static data describing the resource.
	Attributes    []*common.Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stats) GetDroppedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DroppedAt
	}
	return nil
}

func (x *Stats) GetAttributes() []*common.Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// A `PollOp` describes each poll operation that completes within the async
// application.
type PollOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The numeric ID of the op's `Metadata`.
	//
	// This identifies the `Metadata` that describes the `tracing` span
	// corresponding to this op. The metadata for this ID will have been sent
	// in a prior `RegisterMetadata` message.
	Metadata *common.MetaId `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The resources's ID.
	ResourceId *common.Id `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// the name of this op (e.g. poll_elapsed, new_timeout, reset, etc.)
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Identifies the task context that this poll op has been called from.
	TaskId *common.Id `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Identifies the async op ID that this poll op is part of.
	AsyncOpId *common.Id `protobuf:"bytes,6,opt,name=async_op_id,json=asyncOpId,proto3" json:"async_op_id,omitempty"`
	// Whether this poll op has returned with ready or pending.
	IsReady       bool `protobuf:"varint,7,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOp) Reset() {
	*x = PollOp{}
	mi := &file_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOp) ProtoMessage() {}

func (x *PollOp) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOp.ProtoReflect.Descriptor instead.
func (*PollOp) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{3}
}

func (x *PollOp) GetMetadata() *common.MetaId {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PollOp) GetResourceId() *common.Id {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

func (x *PollOp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PollOp) GetTaskId() *common.Id {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *PollOp) GetAsyncOpId() *common.Id {
	if x != nil {
		return x.AsyncOpId
	}
	return nil
}

func (x *PollOp) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

// The kind of resource (e.g. timer, mutex).
type Resource_Kind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every resource is either a known kind or an other (unknown) kind.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Resource_Kind_Known_
	//	*Resource_Kind_Other
	Kind          isResource_Kind_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource_Kind) Reset() {
	*x = Resource_Kind{}
	mi := &file_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource_Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource_Kind) ProtoMessage() {}

func (x *Resource_Kind) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource_Kind.ProtoReflect.Descriptor instead.
func (*Resource_Kind) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Resource_Kind) GetKind() isResource_Kind_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Resource_Kind) GetKnown() Resource_Kind_Known {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Kind_Known_); ok {
			return x.Known
		}
	}
	return Resource_Kind_TIMER
}

func (x *Resource_Kind) GetOther() string {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Kind_Other); ok {
			return x.Other
		}
	}
	return ""
}

type isResource_Kind_Kind interface {
	isResource_Kind_Kind()
}

type Resource_Kind_Known_ struct {
	// `known` signals that this kind of resource is known to the console API.
	Known Resource_Kind_Known `protobuf:"varint,1,opt,name=known,proto3,enum=rs.tokio.console.resources.Resource_Kind_Known,oneof"`
}

type Resource_Kind_Other struct {
	// `other` signals that this kind of resource is unknown to the console API.
	Other string `protobuf:"bytes,2,opt,name=other,proto3,oneof"`
}

func (*Resource_Kind_Known_) isResource_Kind_Kind() {}

func (*Resource_Kind_Other) isResource_Kind_Kind() {}

var File_resources_proto protoreflect.FileDescriptor

const file_resources_proto_rawDesc = "" +
	"\n" +
	"\x0fresources.proto\x12\x1ars.tokio.console.resources\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\fcommon.proto\"\x8b\x03\n" +
	"\x0eResourceUpdate\x12I\n" +
	"\rnew_resources\x18\x01 \x03(\v2$.rs.tokio.console.resources.ResourceR\fnewResources\x12^\n" +
	"\fstats_update\x18\x02 \x03(\v2;.rs.tokio.console.resources.ResourceUpdate.StatsUpdateEntryR\vstatsUpdate\x12D\n" +
	"\fnew_poll_ops\x18\x03 \x03(\v2\".rs.tokio.console.resources.PollOpR\n" +
	"newPollOps\x12%\n" +
	"\x0edropped_events\x18\x04 \x01(\x04R\rdroppedEvents\x1aa\n" +
	"\x10StatsUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.rs.tokio.console.resources.StatsR\x05value:\x028\x01\"\x89\x04\n" +
	"\bResource\x12+\n" +
	"\x02id\x18\x01 \x01(\v2\x1b.rs.tokio.console.common.IdR\x02id\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\bmetadata\x12#\n" +
	"\rconcrete_type\x18\x03 \x01(\tR\fconcreteType\x12=\n" +
	"\x04kind\x18\x04 \x01(\v2).rs.tokio.console.resources.Resource.KindR\x04kind\x12=\n" +
	"\blocation\x18\x05 \x01(\v2!.rs.tokio.console.common.LocationR\blocation\x12I\n" +
	"\x12parent_resource_id\x18\x06 \x01(\v2\x1b.rs.tokio.console.common.IdR\x10parentResourceId\x12\x1f\n" +
	"\vis_internal\x18\a \x01(\bR\n" +
	"isInternal\x1a\x83\x01\n" +
	"\x04Kind\x12G\n" +
	"\x05known\x18\x01 \x01(\x0e2/.rs.tokio.console.resources.Resource.Kind.KnownH\x00R\x05known\x12\x16\n" +
	"\x05other\x18\x02 \x01(\tH\x00R\x05other\"\x12\n" +
	"\x05Known\x12\t\n" +
	"\x05TIMER\x10\x00B\x06\n" +
	"\x04kind\"\xc1\x01\n" +
	"\x05Stats\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"dropped_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdroppedAt\x12B\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\".rs.tokio.console.common.AttributeR\n" +
	"attributes\"\xa5\x02\n" +
	"\x06PollOp\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.rs.tokio.console.common.MetaIdR\bmetadata\x12<\n" +
	"\vresource_id\x18\x03 \x01(\v2\x1b.rs.tokio.console.common.IdR\n" +
	"resourceId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x124\n" +
	"\atask_id\x18\x05 \x01(\v2\x1b.rs.tokio.console.common.IdR\x06taskId\x12;\n" +
	"\vasync_op_id\x18\x06 \x01(\v2\x1b.rs.tokio.console.common.IdR\tasyncOpId\x12\x19\n" +
	"\bis_ready\x18\a \x01(\bR\aisReadyb\x06proto3"

var (
	file_resources_proto_rawDescOnce sync.Once
	file_resources_proto_rawDescData []byte
)

func file_resources_proto_rawDescGZIP() []byte {
	file_resources_proto_rawDescOnce.Do(func() {
		file_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_proto_rawDesc), len(file_resources_proto_rawDesc)))
	})
	return file_resources_proto_rawDescData
}

var file_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resources_proto_goTypes = []any{
	(Resource_Kind_Known)(0),    // 0: rs.tokio.console.resources.Resource.Kind.Known
	(*ResourceUpdate)(nil),      // 1: rs.tokio.console.resources.ResourceUpdate
	(*Resource)(nil),            // 2: rs.tokio.console.resources.Resource
	(*Stats)(nil),               // 3: rs.tokio.console.resources.Stats
	(*PollOp)(nil),              // 4: rs.tokio.console.resources.PollOp
	nil,                         // 5: rs.tokio.console.resources.ResourceUpdate.StatsUpdateEntry
	(*Resource_Kind)(nil),       // 6: rs.tokio.console.resources.Resource.Kind
	(*common.Id)(nil),           // 7: rs.tokio.console.common.Id
	(*common.MetaId)(nil),       // 8: rs.tokio.console.common.MetaId
	(*common.Location)(nil),     // 9: rs.tokio.console.common.Location
	(*timestamp.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*common.Attribute)(nil),    // 11: rs.tokio.console.common.Attribute
}
var file_resources_proto_depIdxs = []int32{
	2,  // 0: rs.tokio.console.resources.ResourceUpdate.new_resources:type_name -> rs.tokio.console.resources.Resource
	5,  // 1: rs.tokio.console.resources.ResourceUpdate.stats_update:type_name -> rs.tokio.console.resources.ResourceUpdate.StatsUpdateEntry
	4,  // 2: rs.tokio.console.resources.ResourceUpdate.new_poll_ops:type_name -> rs.tokio.console.resources.PollOp
	7,  // 3: rs.tokio.console.resources.Resource.id:type_name -> rs.tokio.console.common.Id
	8,  // 4: rs.tokio.console.resources.Resource.metadata:type_name -> rs.tokio.console.common.MetaId
	6,  // 5: rs.tokio.console.resources.Resource.kind:type_name -> rs.tokio.console.resources.Resource.Kind
	9,  // 6: rs.tokio.console.resources.Resource.location:type_name -> rs.tokio.console.common.Location
	7,  // 7: rs.tokio.console.resources.Resource.parent_resource_id:type_name -> rs.tokio.console.common.Id
	10, // 8: rs.tokio.console.resources.Stats.created_at:type_name -> google.protobuf.Timestamp
	10, // 9: rs.tokio.console.resources.Stats.dropped_at:type_name -> google.protobuf.Timestamp
	11, // 10: rs.tokio.console.resources.Stats.attributes:type_name -> rs.tokio.console.common.Attribute
	8,  // 11: rs.tokio.console.resources.PollOp.metadata:type_name -> rs.tokio.console.common.MetaId
	7,  // 12: rs.tokio.console.resources.PollOp.resource_id:type_name -> rs.tokio.console.common.Id
	7,  // 13: rs.tokio.console.resources.PollOp.task_id:type_name -> rs.tokio.console.common.Id
	7,  // 14: rs.tokio.console.resources.PollOp.async_op_id:type_name -> rs.tokio.console.common.Id
	3,  // 15: rs.tokio.console.resources.ResourceUpdate.StatsUpdateEntry.value:type_name -> rs.tokio.console.resources.Stats
	0,  // 16: rs.tokio.console.resources.Resource.Kind.known:type_name -> rs.tokio.console.resources.Resource.Kind.Known
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_resources_proto_init() }
func file_resources_proto_init() {
	if File_resources_proto != nil {
		return
	}
	file_resources_proto_msgTypes[5].OneofWrappers = []any{
		(*Resource_Kind_Known_)(nil),
		(*Resource_Kind_Other)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_proto_rawDesc), len(file_resources_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_proto_goTypes,
		DependencyIndexes: file_resources_proto_depIdxs,
		EnumInfos:         file_resources_proto_enumTypes,
		MessageInfos:      file_resources_proto_msgTypes,
	}.Build()
	File_resources_proto = out.File
	file_resources_proto_goTypes = nil
	file_resources_proto_depIdxs = nil
}
